import type { Platform, Movie, SportEvent } from '@/types';

// Nota: Los logoUrl son obtenidos dinámicamente desde /api/provider-logos (TMDB CDN)
// Solo se usan como fallback inicial hasta que el endpoint responda

export const PLATFORMS: Record<string, Platform> = {
  netflix: {
    id: 'netflix',
    name: 'Netflix',
    shortName: 'N',
    color: '#E50914',
    bgColor: '#E50914',
    textColor: '#ffffff',
    url: 'https://netflix.com',
    type: 'flatrate',
  },
  disneyplus: {
    id: 'disneyplus',
    name: 'Disney+',
    shortName: 'D+',
    color: '#113CCF',
    bgColor: '#113CCF',
    textColor: '#ffffff',
    url: 'https://disneyplus.com',
    type: 'flatrate',
  },
  starplus: {
    id: 'starplus',
    name: 'Star+',
    shortName: 'S+',
    color: '#000000',
    bgColor: '#1a1a2e',
    textColor: '#ffffff',
    url: 'https://starplus.com',
    type: 'flatrate',
  },
  max: {
    id: 'max',
    name: 'Max',
    shortName: 'MAX',
    color: '#002BE7',
    bgColor: '#002BE7',
    textColor: '#ffffff',
    url: 'https://max.com',
    type: 'flatrate',
  },
  prime: {
    id: 'prime',
    name: 'Prime Video',
    shortName: 'PRIME',
    color: '#1399FF',
    bgColor: '#00A8E0',
    textColor: '#ffffff',
    url: 'https://primevideo.com',
    type: 'flatrate',
  },
  paramountplus: {
    id: 'paramountplus',
    name: 'Paramount+',
    shortName: 'P+',
    color: '#0064FF',
    bgColor: '#0064FF',
    textColor: '#ffffff',
    url: 'https://paramountplus.com',
    type: 'flatrate',
  },
  dgo: {
    id: 'dgo',
    name: 'DGO',
    shortName: 'DGO',
    color: '#FF6600',
    bgColor: '#FF6600',
    textColor: '#ffffff',
    url: 'https://dgo.com',
    type: 'flatrate',
  },
  appletv: {
    id: 'appletv',
    name: 'Apple TV+',
    shortName: 'ATV+',
    color: '#555555',
    bgColor: '#1D1D1F',
    textColor: '#ffffff',
    url: 'https://tv.apple.com',
    type: 'flatrate',
  },
  plutotv: {
    id: 'plutotv',
    name: 'Pluto TV',
    shortName: 'PLUTO',
    color: '#F5D900',
    bgColor: '#F5D900',
    textColor: '#000000',
    url: 'https://pluto.tv',
    type: 'free',
  },
  universalplus: {
    id: 'universalplus',
    name: 'Universal+',
    shortName: 'U+',
    color: '#E8891A',
    bgColor: '#E8891A',
    textColor: '#ffffff',
    url: 'https://www.universalplus.com',
    type: 'flatrate',
  },
  crunchyroll: {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    shortName: 'CR',
    color: '#F47521',
    bgColor: '#F47521',
    textColor: '#ffffff',
    url: 'https://crunchyroll.com',
    type: 'flatrate',
  },
  clarovideo: {
    id: 'clarovideo',
    name: 'Claro Video',
    shortName: 'CLARO',
    color: '#DA2128',
    bgColor: '#DA2128',
    textColor: '#ffffff',
    url: 'https://clarovideo.com',
    type: 'flatrate',
  },
  directvgo: {
    id: 'directvgo',
    name: 'DIRECTV GO',
    shortName: 'DTV',
    color: '#00A8FF',
    bgColor: '#0066CC',
    textColor: '#ffffff',
    url: 'https://www.directvgo.com',
    type: 'flatrate',
  },
  mubi: {
    id: 'mubi',
    name: 'MUBI',
    shortName: 'MUBI',
    color: '#1C1C1C',
    bgColor: '#1C1C1C',
    textColor: '#ffffff',
    url: 'https://mubi.com',
    type: 'flatrate',
  },
  movistar: {
    id: 'movistar',
    name: 'MovistarTV',
    shortName: 'MTV',
    color: '#019DF4',
    bgColor: '#019DF4',
    textColor: '#ffffff',
    url: 'https://www.movistar.com.uy',
    type: 'flatrate',
  },
  googleplay: {
    id: 'googleplay',
    name: 'Google Play',
    shortName: 'GPLAY',
    color: '#4285F4',
    bgColor: '#4285F4',
    textColor: '#ffffff',
    url: 'https://play.google.com/store/movies',
    type: 'rent',
  },
  mercadoplay: {
    id: 'mercadoplay',
    name: 'Mercado Play',
    shortName: 'MP',
    color: '#FFE600',
    bgColor: '#FFE600',
    textColor: '#000000',
    url: 'https://www.mercadolibre.com.uy',
    type: 'free',
  },
  curiositystream: {
    id: 'curiositystream',
    name: 'Curiosity Stream',
    shortName: 'CS',
    color: '#F05A28',
    bgColor: '#F05A28',
    textColor: '#ffffff',
    url: 'https://curiositystream.com',
    type: 'flatrate',
  },
  plex: {
    id: 'plex',
    name: 'Plex',
    shortName: 'PLEX',
    color: '#E5A00D',
    bgColor: '#1F1F1F',
    textColor: '#E5A00D',
    url: 'https://www.plex.tv',
    type: 'free',
  },
  viki: {
    id: 'viki',
    name: 'Rakuten Viki',
    shortName: 'VIKI',
    color: '#1DAFE6',
    bgColor: '#1DAFE6',
    textColor: '#ffffff',
    url: 'https://www.viki.com',
    type: 'flatrate',
  },
  vtv: {
    id: 'vtv',
    name: 'VTV',
    shortName: 'VTV',
    color: '#009900',
    bgColor: '#006600',
    textColor: '#ffffff',
    url: 'https://vtv.com.uy',
    type: 'live',
  },
  tenfield: {
    id: 'tenfield',
    name: 'Tenfield',
    shortName: 'TEN',
    color: '#FF4500',
    bgColor: '#CC3300',
    textColor: '#ffffff',
    url: 'https://tenfield.com.uy',
    type: 'live',
  },
  espn: {
    id: 'espn',
    name: 'ESPN',
    shortName: 'ESPN',
    color: '#D00',
    bgColor: '#CC0000',
    textColor: '#ffffff',
    url: 'https://espn.com',
    type: 'live',
  },
};

const p = PLATFORMS;

export const MOVIES: Movie[] = [
  {
    id: 1,
    title: 'Dune: Parte Dos',
    originalTitle: 'Dune: Part Two',
    overview: 'Paul Atreides se une a los Fremen en una guerra de venganza contra los conspiradores que destruyeron a su familia. Debe elegir entre el amor de su vida y el destino del universo.',
    posterPath: 'https://picsum.photos/seed/dune2/300/450',
    backdropPath: 'https://picsum.photos/seed/dune2-back/1280/720',
    voteAverage: 8.3,
    voteCount: 4821,
    releaseDate: '2024-03-01',
    genres: ['Ciencia Ficción', 'Acción', 'Aventura'],
    type: 'movie',
    platforms: [p.max, p.prime],
    tmdbId: 693134,
    runtime: 166,
    isNew: true,
    isTop10: true,
    rank: 1,
  },
  {
    id: 2,
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    overview: 'La historia del físico J. Robert Oppenheimer y su papel en el Proyecto Manhattan, que llevó al desarrollo de la bomba atómica durante la Segunda Guerra Mundial.',
    posterPath: 'https://picsum.photos/seed/oppenheimer/300/450',
    backdropPath: 'https://picsum.photos/seed/oppenheimer-back/1280/720',
    voteAverage: 8.5,
    voteCount: 12430,
    releaseDate: '2023-07-21',
    genres: ['Drama', 'Historia', 'Thriller'],
    type: 'movie',
    platforms: [p.max, p.appletv],
    tmdbId: 872585,
    runtime: 180,
    isTop10: true,
    rank: 2,
  },
  {
    id: 3,
    title: 'Barbie',
    originalTitle: 'Barbie',
    overview: 'Barbie y Ken viven sus mejores días en Barbielandia, pero cuando comienza a pensar en la muerte, ella y Ken son enviados al mundo real para descobrir sus verdaderas identidades.',
    posterPath: 'https://picsum.photos/seed/barbie-movie/300/450',
    backdropPath: 'https://picsum.photos/seed/barbie-back/1280/720',
    voteAverage: 7.1,
    voteCount: 9870,
    releaseDate: '2023-07-21',
    genres: ['Comedia', 'Aventura', 'Fantasía'],
    type: 'movie',
    platforms: [p.max],
    tmdbId: 346698,
    runtime: 114,
    isTop10: true,
    rank: 3,
  },
  {
    id: 4,
    title: 'The Batman',
    originalTitle: 'The Batman',
    overview: 'En su segundo año como Batman, Bruce Wayne debe investigar una serie de crímenes perpetrados por el Acertijo que expone las corrupciones de Gotham City.',
    posterPath: 'https://picsum.photos/seed/thebatman/300/450',
    backdropPath: 'https://picsum.photos/seed/thebatman-back/1280/720',
    voteAverage: 7.8,
    voteCount: 11200,
    releaseDate: '2022-03-04',
    genres: ['Acción', 'Crimen', 'Drama'],
    type: 'movie',
    platforms: [p.max, p.prime],
    tmdbId: 414906,
    runtime: 176,
    isTop10: true,
    rank: 4,
  },
  {
    id: 5,
    title: 'Avatar: El Camino del Agua',
    originalTitle: 'Avatar: The Way of Water',
    overview: 'Jake Sully y Neytiri han formado una familia y hacen todo lo posible por mantenerse unidos. Sin embargo, deben abandonar su hogar y explorar las regiones de Pandora.',
    posterPath: 'https://picsum.photos/seed/avatar2/300/450',
    backdropPath: 'https://picsum.photos/seed/avatar2-back/1280/720',
    voteAverage: 7.6,
    voteCount: 14500,
    releaseDate: '2022-12-16',
    genres: ['Ciencia Ficción', 'Acción', 'Aventura'],
    type: 'movie',
    platforms: [p.disneyplus, p.starplus],
    tmdbId: 76600,
    runtime: 192,
    isTop10: true,
    rank: 5,
  },
  {
    id: 6,
    title: 'Top Gun: Maverick',
    originalTitle: 'Top Gun: Maverick',
    overview: 'Después de más de 30 años de servicio, Pete "Maverick" Mitchell sigue siendo piloto de pruebas, evitando el ascenso en los rangos que lo alejaría del avión que ama.',
    posterPath: 'https://picsum.photos/seed/topgun2/300/450',
    backdropPath: 'https://picsum.photos/seed/topgun2-back/1280/720',
    voteAverage: 8.3,
    voteCount: 13200,
    releaseDate: '2022-05-27',
    genres: ['Acción', 'Drama'],
    type: 'movie',
    platforms: [p.paramountplus, p.netflix],
    tmdbId: 361743,
    runtime: 131,
    isTop10: true,
    rank: 6,
  },
  {
    id: 7,
    title: 'Deadpool & Wolverine',
    originalTitle: 'Deadpool & Wolverine',
    overview: 'Deadpool se une al MCU y busca al inmortal Logan para proteger a su mundo del colapso temporal.',
    posterPath: 'https://picsum.photos/seed/deadpool3/300/450',
    backdropPath: 'https://picsum.photos/seed/deadpool3-back/1280/720',
    voteAverage: 7.6,
    voteCount: 6420,
    releaseDate: '2024-07-26',
    genres: ['Acción', 'Comedia', 'Superhéroes'],
    type: 'movie',
    platforms: [p.disneyplus],
    tmdbId: 533535,
    runtime: 128,
    isNew: true,
    isTop10: true,
    rank: 7,
  },
  {
    id: 8,
    title: 'Intensamente 2',
    originalTitle: 'Inside Out 2',
    overview: 'Riley comienza la secundaria y con ello llegan nuevas emociones: Ansiedad, Ennui, Envidia y Vergüenza. Las antiguas emociones deben luchar por mantener su lugar.',
    posterPath: 'https://picsum.photos/seed/insideout2/300/450',
    backdropPath: 'https://picsum.photos/seed/insideout2-back/1280/720',
    voteAverage: 7.9,
    voteCount: 5200,
    releaseDate: '2024-06-14',
    genres: ['Animación', 'Comedia', 'Familia'],
    type: 'movie',
    platforms: [p.disneyplus],
    tmdbId: 1022789,
    runtime: 100,
    isNew: true,
    isTop10: true,
    rank: 8,
  },
  {
    id: 9,
    title: 'Alien: Romulus',
    originalTitle: 'Alien: Romulus',
    overview: 'Un grupo de jóvenes colonizadores espaciales se encuentran cara a cara con la forma de vida más aterradora del universo mientras intentan sobrevivir.',
    posterPath: 'https://picsum.photos/seed/alienromulus/300/450',
    backdropPath: 'https://picsum.photos/seed/alienromulus-back/1280/720',
    voteAverage: 7.3,
    voteCount: 4100,
    releaseDate: '2024-08-16',
    genres: ['Terror', 'Ciencia Ficción', 'Thriller'],
    type: 'movie',
    platforms: [p.disneyplus, p.starplus],
    tmdbId: 945961,
    runtime: 119,
    isNew: true,
    isTop10: true,
    rank: 9,
  },
  {
    id: 10,
    title: 'El Lobo de Wall Street',
    originalTitle: 'The Wolf of Wall Street',
    overview: 'Basada en la historia real de Jordan Belfort, un corredor de bolsa de Nueva York que construyó un imperó financiero lleno de excesos y corrupción.',
    posterPath: 'https://picsum.photos/seed/wolfwallstreet/300/450',
    backdropPath: 'https://picsum.photos/seed/wolfwallstreet-back/1280/720',
    voteAverage: 8.2,
    voteCount: 18900,
    releaseDate: '2013-12-25',
    genres: ['Crimen', 'Drama', 'Comedia'],
    type: 'movie',
    platforms: [p.netflix, p.prime],
    tmdbId: 106646,
    runtime: 180,
    isTop10: true,
    rank: 10,
  },
  {
    id: 11,
    title: 'Poor Things',
    originalTitle: 'Poor Things',
    overview: 'La increíble historia de la joven Bella Baxter, que vuelve a la vida gracias al brillante y poco convencional científico Dr. Godwin Baxter.',
    posterPath: 'https://picsum.photos/seed/poorthings/300/450',
    backdropPath: 'https://picsum.photos/seed/poorthings-back/1280/720',
    voteAverage: 7.9,
    voteCount: 5800,
    releaseDate: '2023-12-08',
    genres: ['Comedia', 'Drama', 'Fantasía'],
    type: 'movie',
    platforms: [p.prime, p.max],
    tmdbId: 792307,
    runtime: 141,
    isNew: false,
  },
  {
    id: 12,
    title: 'La Sustancia',
    originalTitle: 'The Substance',
    overview: 'Una estrella de Hollywood en declive decide usar una misteriosa sustancia que puede crear una versión más joven y perfecta de sí misma, con consecuencias inesperadas.',
    posterPath: 'https://picsum.photos/seed/thesubstance/300/450',
    backdropPath: 'https://picsum.photos/seed/thesubstance-back/1280/720',
    voteAverage: 7.4,
    voteCount: 3200,
    releaseDate: '2024-09-20',
    genres: ['Terror', 'Ciencia Ficción', 'Drama'],
    type: 'movie',
    platforms: [p.paramountplus],
    tmdbId: 933260,
    runtime: 141,
    isNew: true,
  },
];

export const SERIES: Movie[] = [
  {
    id: 101,
    title: 'Stranger Things',
    originalTitle: 'Stranger Things',
    overview: 'Un grupo de niños de Hawkins, Indiana, se enfrenta a fuerzas sobrenaturales y experimentos secretos del gobierno mientras buscan a su amigo desaparecido.',
    posterPath: 'https://picsum.photos/seed/strangerthings/300/450',
    backdropPath: 'https://picsum.photos/seed/strangerthings-back/1280/720',
    voteAverage: 8.7,
    voteCount: 22300,
    releaseDate: '2016-07-15',
    genres: ['Drama', 'Fantasía', 'Terror'],
    type: 'series',
    platforms: [p.netflix],
    tmdbId: 66732,
    seasons: 4,
    isTop10: false,
  },
  {
    id: 102,
    title: 'The Last of Us',
    originalTitle: 'The Last of Us',
    overview: 'Joel, un superviviente curtido, es contratado para sacar de contrabando a Ellie de una zona de cuarentena opresiva. Lo que comienza como un trabajo se convierte en un viaje brutal.',
    posterPath: 'https://picsum.photos/seed/thelastofus/300/450',
    backdropPath: 'https://picsum.photos/seed/thelastofus-back/1280/720',
    voteAverage: 8.7,
    voteCount: 18900,
    releaseDate: '2023-01-15',
    genres: ['Drama', 'Acción', 'Thriller'],
    type: 'series',
    platforms: [p.max],
    tmdbId: 100088,
    seasons: 2,
    isNew: true,
  },
  {
    id: 103,
    title: 'House of the Dragon',
    originalTitle: 'House of the Dragon',
    overview: 'La historia de la Casa Targaryen, ambientada 200 años antes de los eventos de Juego de Tronos. Una guerra civil entre los miembros de la familia real sacude los Siete Reinos.',
    posterPath: 'https://picsum.photos/seed/housedragon/300/450',
    backdropPath: 'https://picsum.photos/seed/housedragon-back/1280/720',
    voteAverage: 8.4,
    voteCount: 14200,
    releaseDate: '2022-08-21',
    genres: ['Drama', 'Fantasía', 'Acción'],
    type: 'series',
    platforms: [p.max],
    tmdbId: 94997,
    seasons: 2,
    isNew: true,
  },
  {
    id: 104,
    title: 'The Boys',
    originalTitle: 'The Boys',
    overview: 'Un grupo de vigilantes lucha contra los superhéroes que abusan de sus poderes. Un mundo donde los héroes son corrompidos por la fama, el poder y el dinero corporativo.',
    posterPath: 'https://picsum.photos/seed/theboys/300/450',
    backdropPath: 'https://picsum.photos/seed/theboys-back/1280/720',
    voteAverage: 8.7,
    voteCount: 19800,
    releaseDate: '2019-07-26',
    genres: ['Acción', 'Comedia', 'Crimen'],
    type: 'series',
    platforms: [p.prime],
    tmdbId: 76479,
    seasons: 4,
  },
  {
    id: 105,
    title: 'Shogun',
    originalTitle: 'Shogun',
    overview: 'Japón, año 1600. El navegante inglés John Blackthorne queda atrapado en el Japón feudal, donde aprende sus costumbres mientras el país se debate entre guerra y paz.',
    posterPath: 'https://picsum.photos/seed/shogun2024/300/450',
    backdropPath: 'https://picsum.photos/seed/shogun2024-back/1280/720',
    voteAverage: 8.6,
    voteCount: 9400,
    releaseDate: '2024-02-27',
    genres: ['Drama', 'Historia', 'Acción'],
    type: 'series',
    platforms: [p.disneyplus, p.starplus],
    tmdbId: 126308,
    seasons: 1,
    isNew: true,
  },
  {
    id: 106,
    title: 'La Casa de Papel',
    originalTitle: 'La Casa de Papel',
    overview: 'Un misterioso hombre conocido como "El Profesor" recluta a ocho ladrones con alias de ciudades para ejecutar un golpe sin precedentes en la Casa de la Moneda de España.',
    posterPath: 'https://picsum.photos/seed/lacasadepapel/300/450',
    backdropPath: 'https://picsum.photos/seed/lacasadepapel-back/1280/720',
    voteAverage: 8.2,
    voteCount: 24500,
    releaseDate: '2017-05-02',
    genres: ['Crimen', 'Drama', 'Thriller'],
    type: 'series',
    platforms: [p.netflix],
    tmdbId: 71446,
    seasons: 5,
  },
  {
    id: 107,
    title: 'Succession',
    originalTitle: 'Succession',
    overview: 'La familia Roy controla uno de los mayores conglomerados de medios y entretenimiento del mundo. Pero cuando el patriarca empieza a tambalearse, sus hijos librhan una guerra por el poder.',
    posterPath: 'https://picsum.photos/seed/succession/300/450',
    backdropPath: 'https://picsum.photos/seed/succession-back/1280/720',
    voteAverage: 8.9,
    voteCount: 11200,
    releaseDate: '2018-06-03',
    genres: ['Drama', 'Comedia'],
    type: 'series',
    platforms: [p.max],
    tmdbId: 63351,
    seasons: 4,
  },
  {
    id: 108,
    title: 'Reacher',
    originalTitle: 'Reacher',
    overview: 'Jack Reacher, un ex-policía militar del ejército, llega a un pequeño pueblo de Alabama donde es acusado injustamente de asesinato y debe desmantelar una conspiración.',
    posterPath: 'https://picsum.photos/seed/reacher/300/450',
    backdropPath: 'https://picsum.photos/seed/reacher-back/1280/720',
    voteAverage: 7.9,
    voteCount: 8100,
    releaseDate: '2022-02-04',
    genres: ['Acción', 'Crimen', 'Thriller'],
    type: 'series',
    platforms: [p.prime],
    tmdbId: 108978,
    seasons: 3,
    isNew: true,
  },
  {
    id: 109,
    title: 'El Oso',
    originalTitle: 'The Bear',
    overview: 'Carmy, un chef de fine dining, regresa a Chicago para administrar el restaurante familiar de sándwiches tras la muerte de su hermano. El caos culinario y emocional se desata.',
    posterPath: 'https://picsum.photos/seed/thebear/300/450',
    backdropPath: 'https://picsum.photos/seed/thebear-back/1280/720',
    voteAverage: 8.7,
    voteCount: 12800,
    releaseDate: '2022-06-23',
    genres: ['Drama', 'Comedia'],
    type: 'series',
    platforms: [p.disneyplus, p.starplus],
    tmdbId: 136315,
    seasons: 3,
    isNew: true,
  },
  {
    id: 110,
    title: 'Yellowstone',
    originalTitle: 'Yellowstone',
    overview: 'La familia Dutton controla el rancho más grande de los Estados Unidos. Deben defender sus tierras de rivales de todos los lados en el estado de Montana.',
    posterPath: 'https://picsum.photos/seed/yellowstone/300/450',
    backdropPath: 'https://picsum.photos/seed/yellowstone-back/1280/720',
    voteAverage: 8.1,
    voteCount: 9600,
    releaseDate: '2018-06-20',
    genres: ['Drama', 'Western'],
    type: 'series',
    platforms: [p.paramountplus],
    tmdbId: 73586,
    seasons: 5,
  },
];

const now = new Date();
const today = now.toISOString().split('T')[0];
const tomorrow = new Date(now.getTime() + 86400000).toISOString().split('T')[0];
const in2days = new Date(now.getTime() + 2 * 86400000).toISOString().split('T')[0];
const in4days = new Date(now.getTime() + 4 * 86400000).toISOString().split('T')[0];
const in7days = new Date(now.getTime() + 7 * 86400000).toISOString().split('T')[0];

export const SPORT_EVENTS: SportEvent[] = [
  {
    id: 201,
    title: 'Copa Libertadores — Fase de Grupos',
    sport: 'football',
    league: 'Copa CONMEBOL Libertadores 2026',
    teamA: '⚫🟡 Peñarol',
    teamB: '🔵⚪ Nacional',
    date: today,
    time: '20:30',
    timezone: 'UYT',
    platforms: [p.espn, p.dgo],
    isLive: true,
    thumbnailPath: '',
    isUruguay: true,
    description: 'Clásico uruguayo en la Copa Libertadores. Estadio Campeón del Siglo.',
  },
  {
    id: 202,
    title: 'NBA Playoffs — Semifinales',
    sport: 'basketball',
    league: 'NBA Playoffs 2026',
    teamA: '🟢 Boston Celtics',
    teamB: '💛 Golden State Warriors',
    date: today,
    time: '22:30',
    timezone: 'UYT',
    platforms: [p.dgo, p.espn],
    isLive: true,
    thumbnailPath: '',
    description: 'Juego 3 de la serie. Boston lidera 2-0.',
  },
  {
    id: 203,
    title: 'Champions League — Semifinal',
    sport: 'football',
    league: 'UEFA Champions League 2025/26',
    teamA: '⚪ Real Madrid',
    teamB: '🔴 Arsenal',
    date: tomorrow,
    time: '21:00',
    timezone: 'UYT',
    platforms: [p.max, p.espn, p.dgo],
    isLive: false,
    thumbnailPath: '',
    description: 'Vuelta de semis en el Bernabéu. Ida: 1-1 en el Emirates.',
  },
  {
    id: 204,
    title: 'Fórmula 1 — Gran Premio de Miami',
    sport: 'formula1',
    league: 'Fórmula 1 — Temporada 2026',
    teamA: '🔵 Max Verstappen',
    teamB: '🟠 Lando Norris',
    date: in2days,
    time: '17:00',
    timezone: 'UYT',
    platforms: [p.starplus, p.espn],
    isLive: false,
    thumbnailPath: '',
    description: 'Carrera en el Miami International Autodrome. Clasificación el sábado.',
  },
  {
    id: 205,
    title: '🇺🇾 Uruguay vs 🇦🇷 Argentina',
    sport: 'football',
    league: 'Amistoso FIFA — Fecha FIFA Abril 2026',
    teamA: '🇺🇾 Uruguay',
    teamB: '🇦🇷 Argentina',
    date: in4days,
    time: '20:00',
    timezone: 'UYT',
    platforms: [p.vtv, p.tenfield],
    isLive: false,
    thumbnailPath: '',
    isUruguay: true,
    description: 'La Celeste recibe a la actual campeona del mundo en el Estadio Centenario.',
  },
  {
    id: 206,
    title: 'Roland Garros — 3ª Ronda',
    sport: 'tennis',
    league: 'Grand Slam — Roland Garros 2026',
    teamA: '🇪🇸 Carlos Alcaraz',
    teamB: '🇩🇪 Alexander Zverev',
    date: in7days,
    time: '11:00',
    timezone: 'UYT',
    platforms: [p.starplus, p.espn],
    isLive: false,
    thumbnailPath: '',
    description: 'El campeón defensor contra el número 2 del mundo en Philippe-Chatrier.',
  },
];

export const ALL_CONTENT = [...MOVIES, ...SERIES];

export const HERO_SLIDES = [
  { movie: MOVIES[0], tagline: 'El destino del universo está en tus manos.' },
  { movie: MOVIES[1], tagline: 'El hombre que creó la destrucción.' },
  { movie: SERIES[2], tagline: 'Fuego y sangre. La guerra de los dragones.' },
];

// Géneros — deben coincidir exactamente con los que TMDB devuelve en español (es-419)
export const GENRES = [
  'Acción', 'Aventura', 'Animación', 'Comedia', 'Crimen',
  'Drama', 'Fantasía', 'Historia', 'Terror', 'Ciencia ficción',
  'Thriller', 'Western', 'Familia', 'Misterio',
];
